package CLIENT_PAGE;

public class test {

	String html = "<!DOCTYPE html>\n"
			+ "<html lang=\"vi\">\n"
			+ "	<head>\n"
			+ "		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
			+ "		<title>XXIV STORE</title>\n"
			+ "	</head>\n"
			+ "	<body leftmargin=\"0\" marginwidth=\"0\" topmargin=\"0\" marginheight=\"0\" offset=\"0\" style=\"padding: 0;\">\n"
			+ "		<div id=\"wrapper\" dir=\"ltr\" style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%; -webkit-text-size-adjust: none;\">\n"
			+ "			<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\">\n"
			+ "				<tr>\n"
			+ "					<td align=\"center\" valign=\"top\">\n"
			+ "						<div id=\"template_header_image\">\n"
			+ "													</div>\n"
			+ "						<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"template_container\" style=\"background-color: #ffffff; border: 1px solid #dedede; box-shadow: 0 1px 4px rgba(0, 0, 0, 0.1); border-radius: 3px;\">\n"
			+ "							<tr>\n"
			+ "								<td align=\"center\" valign=\"top\">\n"
			+ "									<!-- Header -->\n"
			+ "									<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"template_header\" style='background-color: #2c7596; color: #ffffff; border-bottom: 0; font-weight: bold; line-height: 100%; vertical-align: middle; font-family: \"Helvetica Neue\", Helvetica, Roboto, Arial, sans-serif; border-radius: 3px 3px 0 0;'>\n"
			+ "										<tr>\n"
			+ "											<td id=\"header_wrapper\" style=\"padding: 36px 48px; display: block;\">\n"
			+ "												<h1 style='font-family: \"Helvetica Neue\", Helvetica, Roboto, Arial, sans-serif; font-size: 30px; font-weight: 300; line-height: 150%; margin: 0; text-align: left; text-shadow: 0 1px 0 #5691ab; color: #ffffff; background-color: inherit;'>Chào mừng tới XXIV STORE</h1>\n"
			+ "											</td>\n"
			+ "										</tr>\n"
			+ "									</table>\n"
			+ "									<!-- End Header -->\n"
			+ "								</td>\n"
			+ "							</tr>\n"
			+ "							<tr>\n"
			+ "								<td align=\"center\" valign=\"top\">\n"
			+ "									<!-- Body -->\n"
			+ "									<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"template_body\">\n"
			+ "										<tr>\n"
			+ "											<td valign=\"top\" id=\"body_content\" style=\"background-color: #ffffff;\">\n"
			+ "												<!-- Content -->\n"
			+ "												<table border=\"0\" cellpadding=\"20\" cellspacing=\"0\" width=\"100%\">\n"
			+ "													<tr>\n"
			+ "														<td valign=\"top\" style=\"padding: 48px 48px 32px;\">\n"
			+ "															<div id=\"body_content_inner\" style='color: #636363; font-family: \"Helvetica Neue\", Helvetica, Roboto, Arial, sans-serif; font-size: 14px; line-height: 150%; text-align: left;'>\n"
			+ "\n"
			+ "<p style=\"margin: 0 0 16px;\">Xin chào longnpce170669,</p>\n"
			+ "<p style=\"margin: 0 0 16px;\">Cảm ơn bạn đã tạo tài khoản ở XXIV STORE. Tên tài khoản của bạn là <strong>longnpce170669</strong>. Bạn có thể truy cập trang tài khoản để xem đơn hàng, đổi mật khẩu, và nhiều thứ khác tại: <a href=\"https://xxivstore.com/my-account/\" style=\"color: #2c7596; font-weight: normal; text-decoration: underline;\">https://xxivstore.com/my-account/</a></p>\n"
			+ "		<p style=\"margin: 0 0 16px;\">Mật khẩu của bạn đã được tạo tự động: <strong>9a(&amp;qn0N$I@v</strong></p>\n"
			+ "\n"
			+ "<p style=\"margin: 0 0 16px;\">We look forward to seeing you soon.</p>\n"
			+ "															</div>\n"
			+ "														</td>\n"
			+ "													</tr>\n"
			+ "												</table>\n"
			+ "												<!-- End Content -->\n"
			+ "											</td>\n"
			+ "										</tr>\n"
			+ "									</table>\n"
			+ "									<!-- End Body -->\n"
			+ "								</td>\n"
			+ "							</tr>\n"
			+ "						</table>\n"
			+ "					</td>\n"
			+ "				</tr>\n"
			+ "				<tr>\n"
			+ "					<td align=\"center\" valign=\"top\">\n"
			+ "						<!-- Footer -->\n"
			+ "						<table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"600\" id=\"template_footer\">\n"
			+ "							<tr>\n"
			+ "								<td valign=\"top\" style=\"padding: 0; border-radius: 6px;\">\n"
			+ "									<table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\">\n"
			+ "										<tr>\n"
			+ "											<td colspan=\"2\" valign=\"middle\" id=\"credit\" style='border-radius: 6px; border: 0; color: #8a8a8a; font-family: \"Helvetica Neue\", Helvetica, Roboto, Arial, sans-serif; font-size: 12px; line-height: 150%; text-align: center; padding: 24px 0;'>\n"
			+ "												<p style=\"margin: 0 0 16px;\">XXIV STORE</p>\n"
			+ "											</td>\n"
			+ "										</tr>\n"
			+ "									</table>\n"
			+ "								</td>\n"
			+ "							</tr>\n"
			+ "						</table>\n"
			+ "						<!-- End Footer -->\n"
			+ "					</td>\n"
			+ "				</tr>\n"
			+ "			</table>\n"
			+ "		</div>\n"
			+ "	</body>\n"
			+ "</html>";
}
