vars: {
  page-name: UpdateBrandPage
  controller-name: AdminController
  dao-name: brDAO:BrandDAO
}

label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
      stroke: black
      font-color: black
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

user: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

page: ${page-name}
controller: ${controller-name}
brDAO: ${dao-name}
db: DB {
  width: 100
  height: 50
  shape: cylinder
}

user -> page.view: 1. Fill all brand's attribute and\n click on update button {class: text-black}
page.view -> controller.doGet: 2. doGet() {class: text-black}

controller.doGet -> controller.doGet.updateBrand: 3. updateBrand {class: label right}
controller.doGet.updateBrand -> brDAO.updateBrand: 4. updateBrand {class: text-black}
brDAO.updateBrand -> db.query: 5. executeUpdate {class: text-black}
brDAO.updateBrand <- db.query: 6. return result {class: return arrow}
controller.doGet.updateBrand <- brDAO.updateBrand: 7. return affected row {class: text-black}
alt: {
  affected row = 0: {
    page.view <- controller.doGet: 8. return to Controller {class: text-black}
    user <- page.view: 8.1. Return to update brand\n and show error message {class: text-black}
  }
  else: {
    page.view <- controller.doGet: 9. return to Controller {class: text-black}
    user <- page.view: 9.1. Redirect to brand list {class: text-black}
  }
}

alt.class: frame
